# namelist `physics_flags`

Variable | Type | Default | Description
-------- | ---- | ------- | -----------
`full_flux_surface` | boolean | `false` | Enables full-flux-surface simulation. Should use finite \\( \rho_\ast \\).
`radial_variation` | boolean | `false` | Enables radially global simulation. Should use finite \\( \rho_\ast \\).
`include_parallel_nonlinearity` | boolean | `false` | Include the parallel nonlinearity. Should use finite \\( \rho_\ast \\).
`include_parallel_streaming` | boolean | `true` | Include parallel streaming.
`include_mirror` | boolean | `true` | Include the mirror term.
`nonlinear` | boolean | `false` | Include the \\( \boldsymbol{E \times B} \\) nonlinear term. **Requires `box` grid.**
`adiabatic_option` | boolean | `false` | Controls how the adiabatic species is treated in quasineutrality. Should be one of <ul><li>`no-field-line-average-term` ion adiabatic species, i.e., \\( \delta n_\mathrm{i}/ n = (Z e/T_\mathrm{i}) \varphi \\). </li> <li> `field-line-average-term` electron adiabatic species, i.e., \\( \delta n_\mathrm{e}/ n = (e/T_\mathrm{e}) (\varphi - \langle \varphi \rangle_\psi) \\).</li><li>`default` same as `no-field-line-average-term`</li><li>`iphi00=0` same as `no-field-line-average-term`</li><li>`iphi00=1` same as `no-field-line-average-term`</li><li>`iphi00=2` same as `field-line-average-term`</li></ul>
`const_alpha_geo` | boolean | `false` | 
`include_pressure_variation` | boolean | `true` | Include kinetic profile variation when running radially global simulations. **Setting this to `false` does *not* currently turn everything off.**
`include_geometric_variation` | boolean | `true` | Include magnetic geomety profile variation when running radially global simulations. **Setting this to `false` does *not* currently turn everything off.**
`triangular_ZF` | boolean | `false` | **Deprecated**, use `zonal_init_option = 'triangular'`. Start the zonal (\\( k_y = 0 \\)) potential from a prescribed triangular radial profile, built from the odd \\( k_x \\) harmonics with amplitudes \\( \propto k_x^{-3} \\), rather than from the usual random or single-mode initialisation. Intended for Rosenbluth--Hinton and tertiary-mode studies.
`cos_ZF` | boolean | `false` | **Deprecated**, use `zonal_init_option = 'cosine'`. As `triangular_ZF`, but the prescribed zonal profile is a single cosine in \\( x \\), i.e. only the lowest \\( k_x \\) harmonic is populated.
`triangular_ZF_RH` | boolean | `true` | **Deprecated**, use `zonal_closure_option = 'rh'` (or `'density'` for the old `false`). Project the prescribed zonal profile onto the Rosenbluth--Hinton state, so that the initial distribution is the one that does not decay under parallel streaming or the radial magnetic drift. Inert unless `triangular_ZF` or `cos_ZF` is set.
`triangular_ZF_upar_fac` | real | 1.0 | Interpolates the `triangular_ZF_RH` initial condition between the purely adiabatic response (0.0) and the full Rosenbluth--Hinton projection (1.0).
`triangular_ZF_flow` | boolean | `false` | **Deprecated**, use `zonal_closure_option = 'flow'`. Initialise the zonal distribution as a Maxwellian carrying a parallel flow instead of the Rosenbluth--Hinton state, with \\( u_\parallel \\) set by `triangular_ZF_flow_PS` and `triangular_ZF_flow_sym`. Takes effect only if `triangular_ZF_RH` is `false`.
`triangular_ZF_flow_PS` | real | 1.0 | Weight of the Pfirsch--Schl&uuml;ter return flow in the `triangular_ZF_flow` initialisation. Together with `triangular_ZF_flow_sym` the two scalars span every divergence-free parallel flow that can accompany the \\( \boldsymbol{E \times B} \\) flow: (0,0) is a density perturbation with no flow, (1,0) is pure Pfirsch--Schl&uuml;ter, (0,1) is flow along the direction of symmetry. Both profiles are built by the geometry module and hold at finite aspect ratio and in a stellarator; this pair replaces the earlier `triangular_ZF_PS`/`triangular_ZF_upar` flags, which were these two corners in the large-aspect-ratio limit.
`triangular_ZF_flow_sym` | real | 0.0 | Weight of the flow along the direction of symmetry, which is toroidal in a tokamak. See `triangular_ZF_flow_PS`. Strictly this profile assumes quasisymmetry, and a warning is printed if the geometry does not supply the symmetry direction.
`triangular_ZF_g_exb` | real | 0.0 | Amplitude of the prescribed zonal profile, set as the \\( \boldsymbol{E \times B} \\) shearing rate of its lowest \\( k_x \\) harmonic.
`triangular_ZF_nkx`  | integer | `1` | Radial harmonic the prescribed zonal profile sits on: the profile is placed at \\( k_x = \texttt{triangular\_ZF\_nkx} \times \Delta k_x \\), i.e. array index \\( 1 + \texttt{triangular\_ZF\_nkx} \\). With the default of 1 the profile sits on the lowest \\( k_x \\) and its wavelength is the box length, so it cannot be varied independently of \\( L_x \\); raising `jtwist` then rescales the zonal flow and its shear along with the box, which makes a box-length convergence test meaningless. Raising `jtwist` and `triangular_ZF_nkx` together holds \\( k_x \\) fixed. Must be at least 1 and less than `nakx`.
`zonal_init_option` | string | `none` | How the zonal (\\( k_y = 0 \\)) potential is launched. One of <ul><li>`none` the usual random or single-mode initialisation.</li><li>`cosine` a single cosine in \\( x \\), i.e. only the lowest \\( k_x \\) harmonic.</li><li>`triangular` a triangular radial profile, built from the odd \\( k_x \\) harmonics with amplitudes \\( \\propto k_x^{-3} \\).</li></ul> Replaces the booleans `triangular_ZF` and `cos_ZF`, which are still read but deprecated. The amplitude is set by `triangular_ZF_g_exb`.
`zonal_closure_option` | string | `rh` | Which distribution is put under the prescribed zonal profile, and inert unless `zonal_init_option` is set. One of <ul><li>`density` a density perturbation, \\( g \\propto \\varphi(1-J_0) \\), which satisfies quasineutrality and nothing more.</li><li>`rh` the Rosenbluth--Hinton state, which does not decay under parallel streaming or the radial magnetic drift.</li><li>`flow` a Maxwellian carrying a parallel flow, weighted by `triangular_ZF_flow_PS` and `triangular_ZF_flow_sym`.</li></ul> Replaces the booleans `triangular_ZF_RH` and `triangular_ZF_flow`, which are still read but deprecated.
